#ifndef _OBPPYOCTREE_H_
#define _OBPPYOCTREE_H_

enum
{
	// values 1000.3000 already reserved from includes
	SCRIPTS_GROUP = 10000,
	ADD_NULLS_COUNT,
	ADD_NULLS_RADIUS,
	ADD_NULLS_SEED,
	ADD_NULLS_BUTTON,
	REMOVE_NULLS_BUTTON,

	OCTREE_GROUP,
	OCTREE_MAX_DEPTH,
	OCTREE_MAX_NODE_ELEMENTS,
	OCTREE_RAD,

	QUERY_GROUP,
	QUERY_OBJECT_LINK,
	QUERY_RAD,

	DISPLAY_GROUP,
	DISPLAY_DRAW_NODES,
	DISPLAY_NODE_COLOR,
	DISPLAY_SELECTED_NODE_COLOR,
	DISPLAY_ELEMENT_COLOR,
	DISPLAY_SELECTED_ELEMENT_COLOR,
	DISPLAY_CLOSEST_ELEMENT_COLOR,
	DISPLAY_QUERY_BOX_COLOR,
	DISPLAY_ELEMENT_RADIUS,
	DISPLAY_SELECTED_ELEMENT_RADIUS,
	DISPLAY_CLOSEST_ELEMENT_RADIUS

};

#endif