CONTAINER Obppyoctree
{
	NAME Obppyoctree;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{

	    GROUP SCRIPTS_GROUP
	    {
	        DEFAULT 1;
	        LONG ADD_NULLS_COUNT {MIN 1;}
	        REAL ADD_NULLS_RADIUS {UNIT METER; MIN 0.0;}
	        LONG ADD_NULLS_SEED {MIN 0;}
	        BUTTON ADD_NULLS_BUTTON {}
	        BUTTON REMOVE_NULLS_BUTTON {}
	    }

	    GROUP OCTREE_GROUP
	    {
	        DEFAULT 1;
	        LONG OCTREE_MAX_DEPTH{MIN 0;}
	        LONG OCTREE_MAX_NODE_ELEMENTS{MIN 1;}
	        REAL OCTREE_RAD{UNIT METER; MIN 1.0;}
	    }

	    GROUP QUERY_GROUP
	    {
	        DEFAULT 1;
	        LINK QUERY_OBJECT_LINK{ACCEPT { Onull;}}
	        REAL QUERY_RAD{UNIT METER; MIN 1.0;}
	    }

	    GROUP DISPLAY_GROUP
	    {
	        DEFAULT 1;
	        BOOL DISPLAY_DRAW_NODES{}
	        COLOR DISPLAY_NODE_COLOR{}
	        COLOR DISPLAY_SELECTED_NODE_COLOR{}
	        COLOR DISPLAY_ELEMENT_COLOR{}
	        COLOR DISPLAY_SELECTED_ELEMENT_COLOR{}
	        COLOR DISPLAY_CLOSEST_ELEMENT_COLOR{}
	        COLOR DISPLAY_QUERY_BOX_COLOR{}
	        REAL DISPLAY_ELEMENT_RADIUS{UNIT METER; MIN 0.001;}
	        REAL DISPLAY_SELECTED_ELEMENT_RADIUS{UNIT METER; MIN 0.001;}
	        REAL DISPLAY_CLOSEST_ELEMENT_RADIUS{UNIT METER; MIN 0.001;}
	    }

	}

}